/* tslint:disable */
/* eslint-disable */
/**
 * Service Tableau d\'Assemblage
 * API pour accéder aux données du tableau d\'assemblage, y compris les couches chantier, filtres et produits téléchargeables.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChantierGet200Response,
  FiltreGet200Response,
  ProduitGet200Response,
} from '../models/index';
import {
    ChantierGet200ResponseFromJSON,
    ChantierGet200ResponseToJSON,
    FiltreGet200ResponseFromJSON,
    FiltreGet200ResponseToJSON,
    ProduitGet200ResponseFromJSON,
    ProduitGet200ResponseToJSON,
} from '../models/index';

export interface ChantierGetRequest {
    service: string;
    version: string;
    apiKey: string;
    request: string;
    typeNames: string;
    outputFormat: string;
    srsName: string;
}

export interface FiltreGetRequest {
    service: string;
    version: string;
    apiKey: string;
    request: string;
    typeNames: string;
    outputFormat: string;
    srsName: string;
}

export interface ProduitGetRequest {
    service: string;
    version: string;
    apiKey: string;
    request: string;
    typeNames: string;
    outputFormat: string;
    srsName: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Retourne les chantier disponibles selon le produit et l\'emprise.
     * Récupérer les chantiers disponibles pour un produit
     */
    async chantierGetRaw(requestParameters: ChantierGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChantierGet200Response>> {
        if (requestParameters['service'] == null) {
            throw new runtime.RequiredError(
                'service',
                'Required parameter "service" was null or undefined when calling chantierGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling chantierGet().'
            );
        }

        if (requestParameters['apiKey'] == null) {
            throw new runtime.RequiredError(
                'apiKey',
                'Required parameter "apiKey" was null or undefined when calling chantierGet().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling chantierGet().'
            );
        }

        if (requestParameters['typeNames'] == null) {
            throw new runtime.RequiredError(
                'typeNames',
                'Required parameter "typeNames" was null or undefined when calling chantierGet().'
            );
        }

        if (requestParameters['outputFormat'] == null) {
            throw new runtime.RequiredError(
                'outputFormat',
                'Required parameter "outputFormat" was null or undefined when calling chantierGet().'
            );
        }

        if (requestParameters['srsName'] == null) {
            throw new runtime.RequiredError(
                'srsName',
                'Required parameter "srsName" was null or undefined when calling chantierGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['service'] != null) {
            queryParameters['service'] = requestParameters['service'];
        }

        if (requestParameters['version'] != null) {
            queryParameters['version'] = requestParameters['version'];
        }

        if (requestParameters['apiKey'] != null) {
            queryParameters['apiKey'] = requestParameters['apiKey'];
        }

        if (requestParameters['request'] != null) {
            queryParameters['request'] = requestParameters['request'];
        }

        if (requestParameters['typeNames'] != null) {
            queryParameters['typeNames'] = requestParameters['typeNames'];
        }

        if (requestParameters['outputFormat'] != null) {
            queryParameters['outputFormat'] = requestParameters['outputFormat'];
        }

        if (requestParameters['srsName'] != null) {
            queryParameters['srsName'] = requestParameters['srsName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chantier`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChantierGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Retourne les chantier disponibles selon le produit et l\'emprise.
     * Récupérer les chantiers disponibles pour un produit
     */
    async chantierGet(requestParameters: ChantierGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChantierGet200Response> {
        const response = await this.chantierGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Cette route permet de récupérer les filtres existants pour les données et chantiers d\'un produit, incluant des options de recherche, de sélection et d\'affichage.
     * Récupérer les filtres existants
     */
    async filtreGetRaw(requestParameters: FiltreGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FiltreGet200Response>> {
        if (requestParameters['service'] == null) {
            throw new runtime.RequiredError(
                'service',
                'Required parameter "service" was null or undefined when calling filtreGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling filtreGet().'
            );
        }

        if (requestParameters['apiKey'] == null) {
            throw new runtime.RequiredError(
                'apiKey',
                'Required parameter "apiKey" was null or undefined when calling filtreGet().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling filtreGet().'
            );
        }

        if (requestParameters['typeNames'] == null) {
            throw new runtime.RequiredError(
                'typeNames',
                'Required parameter "typeNames" was null or undefined when calling filtreGet().'
            );
        }

        if (requestParameters['outputFormat'] == null) {
            throw new runtime.RequiredError(
                'outputFormat',
                'Required parameter "outputFormat" was null or undefined when calling filtreGet().'
            );
        }

        if (requestParameters['srsName'] == null) {
            throw new runtime.RequiredError(
                'srsName',
                'Required parameter "srsName" was null or undefined when calling filtreGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['service'] != null) {
            queryParameters['service'] = requestParameters['service'];
        }

        if (requestParameters['version'] != null) {
            queryParameters['version'] = requestParameters['version'];
        }

        if (requestParameters['apiKey'] != null) {
            queryParameters['apiKey'] = requestParameters['apiKey'];
        }

        if (requestParameters['request'] != null) {
            queryParameters['request'] = requestParameters['request'];
        }

        if (requestParameters['typeNames'] != null) {
            queryParameters['typeNames'] = requestParameters['typeNames'];
        }

        if (requestParameters['outputFormat'] != null) {
            queryParameters['outputFormat'] = requestParameters['outputFormat'];
        }

        if (requestParameters['srsName'] != null) {
            queryParameters['srsName'] = requestParameters['srsName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/filtre`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FiltreGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Cette route permet de récupérer les filtres existants pour les données et chantiers d\'un produit, incluant des options de recherche, de sélection et d\'affichage.
     * Récupérer les filtres existants
     */
    async filtreGet(requestParameters: FiltreGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FiltreGet200Response> {
        const response = await this.filtreGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retourne les informations sur le produit avec les liens pour télécharger les données.
     * Récupérer les infos sur les données disponibles du produit à télécharger
     */
    async produitGetRaw(requestParameters: ProduitGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProduitGet200Response>> {
        if (requestParameters['service'] == null) {
            throw new runtime.RequiredError(
                'service',
                'Required parameter "service" was null or undefined when calling produitGet().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling produitGet().'
            );
        }

        if (requestParameters['apiKey'] == null) {
            throw new runtime.RequiredError(
                'apiKey',
                'Required parameter "apiKey" was null or undefined when calling produitGet().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling produitGet().'
            );
        }

        if (requestParameters['typeNames'] == null) {
            throw new runtime.RequiredError(
                'typeNames',
                'Required parameter "typeNames" was null or undefined when calling produitGet().'
            );
        }

        if (requestParameters['outputFormat'] == null) {
            throw new runtime.RequiredError(
                'outputFormat',
                'Required parameter "outputFormat" was null or undefined when calling produitGet().'
            );
        }

        if (requestParameters['srsName'] == null) {
            throw new runtime.RequiredError(
                'srsName',
                'Required parameter "srsName" was null or undefined when calling produitGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['service'] != null) {
            queryParameters['service'] = requestParameters['service'];
        }

        if (requestParameters['version'] != null) {
            queryParameters['version'] = requestParameters['version'];
        }

        if (requestParameters['apiKey'] != null) {
            queryParameters['apiKey'] = requestParameters['apiKey'];
        }

        if (requestParameters['request'] != null) {
            queryParameters['request'] = requestParameters['request'];
        }

        if (requestParameters['typeNames'] != null) {
            queryParameters['typeNames'] = requestParameters['typeNames'];
        }

        if (requestParameters['outputFormat'] != null) {
            queryParameters['outputFormat'] = requestParameters['outputFormat'];
        }

        if (requestParameters['srsName'] != null) {
            queryParameters['srsName'] = requestParameters['srsName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/produit`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProduitGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Retourne les informations sur le produit avec les liens pour télécharger les données.
     * Récupérer les infos sur les données disponibles du produit à télécharger
     */
    async produitGet(requestParameters: ProduitGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProduitGet200Response> {
        const response = await this.produitGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
