/* tslint:disable */
/* eslint-disable */
/**
 * Service Tableau d\'Assemblage
 * API pour accéder aux données du tableau d\'assemblage, y compris les couches chantier, filtres et produits téléchargeables.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChantierGet200ResponseFeaturesInnerGeometry
 */
export interface ChantierGet200ResponseFeaturesInnerGeometry {
    /**
     * 
     * @type {string}
     * @memberof ChantierGet200ResponseFeaturesInnerGeometry
     */
    type?: string;
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof ChantierGet200ResponseFeaturesInnerGeometry
     */
    coordinates?: Array<Array<number>>;
}

/**
 * Check if a given object implements the ChantierGet200ResponseFeaturesInnerGeometry interface.
 */
export function instanceOfChantierGet200ResponseFeaturesInnerGeometry(value: object): value is ChantierGet200ResponseFeaturesInnerGeometry {
    return true;
}

export function ChantierGet200ResponseFeaturesInnerGeometryFromJSON(json: any): ChantierGet200ResponseFeaturesInnerGeometry {
    return ChantierGet200ResponseFeaturesInnerGeometryFromJSONTyped(json, false);
}

export function ChantierGet200ResponseFeaturesInnerGeometryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChantierGet200ResponseFeaturesInnerGeometry {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'coordinates': json['coordinates'] == null ? undefined : json['coordinates'],
    };
}

export function ChantierGet200ResponseFeaturesInnerGeometryToJSON(json: any): ChantierGet200ResponseFeaturesInnerGeometry {
    return ChantierGet200ResponseFeaturesInnerGeometryToJSONTyped(json, false);
}

export function ChantierGet200ResponseFeaturesInnerGeometryToJSONTyped(value?: ChantierGet200ResponseFeaturesInnerGeometry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'coordinates': value['coordinates'],
    };
}

