/* tslint:disable */
/* eslint-disable */
/**
 * Service Tableau d\'Assemblage
 * API pour accéder aux données du tableau d\'assemblage, y compris les couches chantier, filtres et produits téléchargeables.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChantierGet200ResponseFeaturesInner } from './ChantierGet200ResponseFeaturesInner';
import {
    ChantierGet200ResponseFeaturesInnerFromJSON,
    ChantierGet200ResponseFeaturesInnerFromJSONTyped,
    ChantierGet200ResponseFeaturesInnerToJSON,
    ChantierGet200ResponseFeaturesInnerToJSONTyped,
} from './ChantierGet200ResponseFeaturesInner';

/**
 * 
 * @export
 * @interface ChantierGet200Response
 */
export interface ChantierGet200Response {
    /**
     * 
     * @type {string}
     * @memberof ChantierGet200Response
     */
    type?: string;
    /**
     * 
     * @type {Array<ChantierGet200ResponseFeaturesInner>}
     * @memberof ChantierGet200Response
     */
    features?: Array<ChantierGet200ResponseFeaturesInner>;
}

/**
 * Check if a given object implements the ChantierGet200Response interface.
 */
export function instanceOfChantierGet200Response(value: object): value is ChantierGet200Response {
    return true;
}

export function ChantierGet200ResponseFromJSON(json: any): ChantierGet200Response {
    return ChantierGet200ResponseFromJSONTyped(json, false);
}

export function ChantierGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChantierGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'features': json['features'] == null ? undefined : ((json['features'] as Array<any>).map(ChantierGet200ResponseFeaturesInnerFromJSON)),
    };
}

export function ChantierGet200ResponseToJSON(json: any): ChantierGet200Response {
    return ChantierGet200ResponseToJSONTyped(json, false);
}

export function ChantierGet200ResponseToJSONTyped(value?: ChantierGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'features': value['features'] == null ? undefined : ((value['features'] as Array<any>).map(ChantierGet200ResponseFeaturesInnerToJSON)),
    };
}

