/* tslint:disable */
/* eslint-disable */
/**
 * Service Tableau d\'Assemblage
 * API pour accéder aux données du tableau d\'assemblage, y compris les couches chantier, filtres et produits téléchargeables.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChantierGet200ResponseFeaturesInnerProperties } from './ChantierGet200ResponseFeaturesInnerProperties';
import {
    ChantierGet200ResponseFeaturesInnerPropertiesFromJSON,
    ChantierGet200ResponseFeaturesInnerPropertiesFromJSONTyped,
    ChantierGet200ResponseFeaturesInnerPropertiesToJSON,
    ChantierGet200ResponseFeaturesInnerPropertiesToJSONTyped,
} from './ChantierGet200ResponseFeaturesInnerProperties';
import type { ChantierGet200ResponseFeaturesInnerGeometry } from './ChantierGet200ResponseFeaturesInnerGeometry';
import {
    ChantierGet200ResponseFeaturesInnerGeometryFromJSON,
    ChantierGet200ResponseFeaturesInnerGeometryFromJSONTyped,
    ChantierGet200ResponseFeaturesInnerGeometryToJSON,
    ChantierGet200ResponseFeaturesInnerGeometryToJSONTyped,
} from './ChantierGet200ResponseFeaturesInnerGeometry';

/**
 * 
 * @export
 * @interface ChantierGet200ResponseFeaturesInner
 */
export interface ChantierGet200ResponseFeaturesInner {
    /**
     * 
     * @type {string}
     * @memberof ChantierGet200ResponseFeaturesInner
     */
    type?: string;
    /**
     * 
     * @type {ChantierGet200ResponseFeaturesInnerGeometry}
     * @memberof ChantierGet200ResponseFeaturesInner
     */
    geometry?: ChantierGet200ResponseFeaturesInnerGeometry;
    /**
     * 
     * @type {ChantierGet200ResponseFeaturesInnerProperties}
     * @memberof ChantierGet200ResponseFeaturesInner
     */
    properties?: ChantierGet200ResponseFeaturesInnerProperties;
}

/**
 * Check if a given object implements the ChantierGet200ResponseFeaturesInner interface.
 */
export function instanceOfChantierGet200ResponseFeaturesInner(value: object): value is ChantierGet200ResponseFeaturesInner {
    return true;
}

export function ChantierGet200ResponseFeaturesInnerFromJSON(json: any): ChantierGet200ResponseFeaturesInner {
    return ChantierGet200ResponseFeaturesInnerFromJSONTyped(json, false);
}

export function ChantierGet200ResponseFeaturesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChantierGet200ResponseFeaturesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'geometry': json['geometry'] == null ? undefined : ChantierGet200ResponseFeaturesInnerGeometryFromJSON(json['geometry']),
        'properties': json['properties'] == null ? undefined : ChantierGet200ResponseFeaturesInnerPropertiesFromJSON(json['properties']),
    };
}

export function ChantierGet200ResponseFeaturesInnerToJSON(json: any): ChantierGet200ResponseFeaturesInner {
    return ChantierGet200ResponseFeaturesInnerToJSONTyped(json, false);
}

export function ChantierGet200ResponseFeaturesInnerToJSONTyped(value?: ChantierGet200ResponseFeaturesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'geometry': ChantierGet200ResponseFeaturesInnerGeometryToJSON(value['geometry']),
        'properties': ChantierGet200ResponseFeaturesInnerPropertiesToJSON(value['properties']),
    };
}

