/* tslint:disable */
/* eslint-disable */
/**
 * Service Tableau d\'Assemblage
 * API pour accéder aux données du tableau d\'assemblage, y compris les couches chantier, filtres et produits téléchargeables.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChantierGet200ResponseFeaturesInnerProperties
 */
export interface ChantierGet200ResponseFeaturesInnerProperties {
    /**
     * Identifiant unique
     * @type {number}
     * @memberof ChantierGet200ResponseFeaturesInnerProperties
     */
    id?: number;
    /**
     * Nom du chantier
     * @type {string}
     * @memberof ChantierGet200ResponseFeaturesInnerProperties
     */
    name?: string;
    /**
     * Date de création du chantier
     * @type {Date}
     * @memberof ChantierGet200ResponseFeaturesInnerProperties
     */
    timestamp?: Date;
    /**
     * Legende qui sera affiché au survol d'un chantier
     * @type {string}
     * @memberof ChantierGet200ResponseFeaturesInnerProperties
     */
    legend?: string;
    /**
     * Url de téléchargement de ma donnée
     * @type {string}
     * @memberof ChantierGet200ResponseFeaturesInnerProperties
     */
    metadonneesLot?: string;
    /**
     * Niveau d'apparition de la couche
     * @type {number}
     * @memberof ChantierGet200ResponseFeaturesInnerProperties
     */
    zoomStart?: number;
    /**
     * Niveau de disparition de la couche
     * @type {number}
     * @memberof ChantierGet200ResponseFeaturesInnerProperties
     */
    zoomStop?: number;
    /**
     * Indique si la couche chantier doit être affiché
     * @type {boolean}
     * @memberof ChantierGet200ResponseFeaturesInnerProperties
     */
    affichageChantier?: boolean;
}

/**
 * Check if a given object implements the ChantierGet200ResponseFeaturesInnerProperties interface.
 */
export function instanceOfChantierGet200ResponseFeaturesInnerProperties(value: object): value is ChantierGet200ResponseFeaturesInnerProperties {
    return true;
}

export function ChantierGet200ResponseFeaturesInnerPropertiesFromJSON(json: any): ChantierGet200ResponseFeaturesInnerProperties {
    return ChantierGet200ResponseFeaturesInnerPropertiesFromJSONTyped(json, false);
}

export function ChantierGet200ResponseFeaturesInnerPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChantierGet200ResponseFeaturesInnerProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'legend': json['legend'] == null ? undefined : json['legend'],
        'metadonneesLot': json['metadonnees_lot'] == null ? undefined : json['metadonnees_lot'],
        'zoomStart': json['zoomStart'] == null ? undefined : json['zoomStart'],
        'zoomStop': json['zoomStop'] == null ? undefined : json['zoomStop'],
        'affichageChantier': json['affichage_chantier'] == null ? undefined : json['affichage_chantier'],
    };
}

export function ChantierGet200ResponseFeaturesInnerPropertiesToJSON(json: any): ChantierGet200ResponseFeaturesInnerProperties {
    return ChantierGet200ResponseFeaturesInnerPropertiesToJSONTyped(json, false);
}

export function ChantierGet200ResponseFeaturesInnerPropertiesToJSONTyped(value?: ChantierGet200ResponseFeaturesInnerProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString().substring(0,10)),
        'legend': value['legend'],
        'metadonnees_lot': value['metadonneesLot'],
        'zoomStart': value['zoomStart'],
        'zoomStop': value['zoomStop'],
        'affichage_chantier': value['affichageChantier'],
    };
}

