/* tslint:disable */
/* eslint-disable */
/**
 * Service Tableau d\'Assemblage
 * API pour accéder aux données du tableau d\'assemblage, y compris les couches chantier, filtres et produits téléchargeables.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FiltreGet200ResponseFeaturesInnerProperties } from './FiltreGet200ResponseFeaturesInnerProperties';
import {
    FiltreGet200ResponseFeaturesInnerPropertiesFromJSON,
    FiltreGet200ResponseFeaturesInnerPropertiesFromJSONTyped,
    FiltreGet200ResponseFeaturesInnerPropertiesToJSON,
    FiltreGet200ResponseFeaturesInnerPropertiesToJSONTyped,
} from './FiltreGet200ResponseFeaturesInnerProperties';

/**
 * 
 * @export
 * @interface FiltreGet200ResponseFeaturesInner
 */
export interface FiltreGet200ResponseFeaturesInner {
    /**
     * 
     * @type {string}
     * @memberof FiltreGet200ResponseFeaturesInner
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof FiltreGet200ResponseFeaturesInner
     */
    geometry?: string;
    /**
     * 
     * @type {FiltreGet200ResponseFeaturesInnerProperties}
     * @memberof FiltreGet200ResponseFeaturesInner
     */
    properties?: FiltreGet200ResponseFeaturesInnerProperties;
}

/**
 * Check if a given object implements the FiltreGet200ResponseFeaturesInner interface.
 */
export function instanceOfFiltreGet200ResponseFeaturesInner(value: object): value is FiltreGet200ResponseFeaturesInner {
    return true;
}

export function FiltreGet200ResponseFeaturesInnerFromJSON(json: any): FiltreGet200ResponseFeaturesInner {
    return FiltreGet200ResponseFeaturesInnerFromJSONTyped(json, false);
}

export function FiltreGet200ResponseFeaturesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiltreGet200ResponseFeaturesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'geometry': json['geometry'] == null ? undefined : json['geometry'],
        'properties': json['properties'] == null ? undefined : FiltreGet200ResponseFeaturesInnerPropertiesFromJSON(json['properties']),
    };
}

export function FiltreGet200ResponseFeaturesInnerToJSON(json: any): FiltreGet200ResponseFeaturesInner {
    return FiltreGet200ResponseFeaturesInnerToJSONTyped(json, false);
}

export function FiltreGet200ResponseFeaturesInnerToJSONTyped(value?: FiltreGet200ResponseFeaturesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'geometry': value['geometry'],
        'properties': FiltreGet200ResponseFeaturesInnerPropertiesToJSON(value['properties']),
    };
}

