/* tslint:disable */
/* eslint-disable */
/**
 * Service Tableau d\'Assemblage
 * API pour accéder aux données du tableau d\'assemblage, y compris les couches chantier, filtres et produits téléchargeables.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FiltreGet200ResponseFeaturesInner } from './FiltreGet200ResponseFeaturesInner';
import {
    FiltreGet200ResponseFeaturesInnerFromJSON,
    FiltreGet200ResponseFeaturesInnerFromJSONTyped,
    FiltreGet200ResponseFeaturesInnerToJSON,
    FiltreGet200ResponseFeaturesInnerToJSONTyped,
} from './FiltreGet200ResponseFeaturesInner';

/**
 * 
 * @export
 * @interface FiltreGet200Response
 */
export interface FiltreGet200Response {
    /**
     * 
     * @type {string}
     * @memberof FiltreGet200Response
     */
    type?: string;
    /**
     * 
     * @type {Array<FiltreGet200ResponseFeaturesInner>}
     * @memberof FiltreGet200Response
     */
    features?: Array<FiltreGet200ResponseFeaturesInner>;
}

/**
 * Check if a given object implements the FiltreGet200Response interface.
 */
export function instanceOfFiltreGet200Response(value: object): value is FiltreGet200Response {
    return true;
}

export function FiltreGet200ResponseFromJSON(json: any): FiltreGet200Response {
    return FiltreGet200ResponseFromJSONTyped(json, false);
}

export function FiltreGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiltreGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'features': json['features'] == null ? undefined : ((json['features'] as Array<any>).map(FiltreGet200ResponseFeaturesInnerFromJSON)),
    };
}

export function FiltreGet200ResponseToJSON(json: any): FiltreGet200Response {
    return FiltreGet200ResponseToJSONTyped(json, false);
}

export function FiltreGet200ResponseToJSONTyped(value?: FiltreGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'features': value['features'] == null ? undefined : ((value['features'] as Array<any>).map(FiltreGet200ResponseFeaturesInnerToJSON)),
    };
}

