/* tslint:disable */
/* eslint-disable */
/**
 * Service Tableau d\'Assemblage
 * API pour accéder aux données du tableau d\'assemblage, y compris les couches chantier, filtres et produits téléchargeables.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FiltreGet200ResponseFeaturesInnerPropertiesChantierInner } from './FiltreGet200ResponseFeaturesInnerPropertiesChantierInner';
import {
    FiltreGet200ResponseFeaturesInnerPropertiesChantierInnerFromJSON,
    FiltreGet200ResponseFeaturesInnerPropertiesChantierInnerFromJSONTyped,
    FiltreGet200ResponseFeaturesInnerPropertiesChantierInnerToJSON,
    FiltreGet200ResponseFeaturesInnerPropertiesChantierInnerToJSONTyped,
} from './FiltreGet200ResponseFeaturesInnerPropertiesChantierInner';

/**
 * 
 * @export
 * @interface FiltreGet200ResponseFeaturesInnerProperties
 */
export interface FiltreGet200ResponseFeaturesInnerProperties {
    /**
     * Identifiant unique
     * @type {string}
     * @memberof FiltreGet200ResponseFeaturesInnerProperties
     */
    id?: string;
    /**
     * Nom du produit associé aux filtres
     * @type {string}
     * @memberof FiltreGet200ResponseFeaturesInnerProperties
     */
    name?: string;
    /**
     * Date de la plus vielle donnée disponible
     * @type {Date}
     * @memberof FiltreGet200ResponseFeaturesInnerProperties
     */
    timestampStart?: Date;
    /**
     * Liste des chantiers disponibles pour le produit
     * @type {Array<FiltreGet200ResponseFeaturesInnerPropertiesChantierInner>}
     * @memberof FiltreGet200ResponseFeaturesInnerProperties
     */
    chantier?: Array<FiltreGet200ResponseFeaturesInnerPropertiesChantierInner>;
    /**
     * Indique si le fonctionnalité recherche par ville département ou région doit etre activé
     * @type {boolean}
     * @memberof FiltreGet200ResponseFeaturesInnerProperties
     */
    recherche?: boolean;
    /**
     * Indique les méthodes possible de séléction sur la carte pour le produit
     * @type {Array<string>}
     * @memberof FiltreGet200ResponseFeaturesInnerProperties
     */
    modeSelection?: Array<FiltreGet200ResponseFeaturesInnerPropertiesModeSelectionEnum>;
    /**
     * indique les fond de cartes à utiliser
     * @type {Array<string>}
     * @memberof FiltreGet200ResponseFeaturesInnerProperties
     */
    cartes?: Array<string>;
}


/**
 * @export
 */
export const FiltreGet200ResponseFeaturesInnerPropertiesModeSelectionEnum = {
    Clic: 'clic',
    Rectangle: 'rectangle',
    Polygone: 'polygone',
    Geojson: 'geojson',
    Shp: 'shp',
    Recherche: 'recherche'
} as const;
export type FiltreGet200ResponseFeaturesInnerPropertiesModeSelectionEnum = typeof FiltreGet200ResponseFeaturesInnerPropertiesModeSelectionEnum[keyof typeof FiltreGet200ResponseFeaturesInnerPropertiesModeSelectionEnum];


/**
 * Check if a given object implements the FiltreGet200ResponseFeaturesInnerProperties interface.
 */
export function instanceOfFiltreGet200ResponseFeaturesInnerProperties(value: object): value is FiltreGet200ResponseFeaturesInnerProperties {
    return true;
}

export function FiltreGet200ResponseFeaturesInnerPropertiesFromJSON(json: any): FiltreGet200ResponseFeaturesInnerProperties {
    return FiltreGet200ResponseFeaturesInnerPropertiesFromJSONTyped(json, false);
}

export function FiltreGet200ResponseFeaturesInnerPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiltreGet200ResponseFeaturesInnerProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'timestampStart': json['timestampStart'] == null ? undefined : (new Date(json['timestampStart'])),
        'chantier': json['chantier'] == null ? undefined : ((json['chantier'] as Array<any>).map(FiltreGet200ResponseFeaturesInnerPropertiesChantierInnerFromJSON)),
        'recherche': json['recherche'] == null ? undefined : json['recherche'],
        'modeSelection': json['mode_selection'] == null ? undefined : json['mode_selection'],
        'cartes': json['cartes'] == null ? undefined : json['cartes'],
    };
}

export function FiltreGet200ResponseFeaturesInnerPropertiesToJSON(json: any): FiltreGet200ResponseFeaturesInnerProperties {
    return FiltreGet200ResponseFeaturesInnerPropertiesToJSONTyped(json, false);
}

export function FiltreGet200ResponseFeaturesInnerPropertiesToJSONTyped(value?: FiltreGet200ResponseFeaturesInnerProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'timestampStart': value['timestampStart'] == null ? undefined : ((value['timestampStart']).toISOString()),
        'chantier': value['chantier'] == null ? undefined : ((value['chantier'] as Array<any>).map(FiltreGet200ResponseFeaturesInnerPropertiesChantierInnerToJSON)),
        'recherche': value['recherche'],
        'mode_selection': value['modeSelection'],
        'cartes': value['cartes'],
    };
}

