/* tslint:disable */
/* eslint-disable */
/**
 * Service Tableau d\'Assemblage
 * API pour accéder aux données du tableau d\'assemblage, y compris les couches chantier, filtres et produits téléchargeables.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FiltreGet200ResponseFeaturesInnerPropertiesChantierInner
 */
export interface FiltreGet200ResponseFeaturesInnerPropertiesChantierInner {
    /**
     * 
     * @type {number}
     * @memberof FiltreGet200ResponseFeaturesInnerPropertiesChantierInner
     */
    idChantier?: number;
    /**
     * 
     * @type {string}
     * @memberof FiltreGet200ResponseFeaturesInnerPropertiesChantierInner
     */
    nom?: string;
}

/**
 * Check if a given object implements the FiltreGet200ResponseFeaturesInnerPropertiesChantierInner interface.
 */
export function instanceOfFiltreGet200ResponseFeaturesInnerPropertiesChantierInner(value: object): value is FiltreGet200ResponseFeaturesInnerPropertiesChantierInner {
    return true;
}

export function FiltreGet200ResponseFeaturesInnerPropertiesChantierInnerFromJSON(json: any): FiltreGet200ResponseFeaturesInnerPropertiesChantierInner {
    return FiltreGet200ResponseFeaturesInnerPropertiesChantierInnerFromJSONTyped(json, false);
}

export function FiltreGet200ResponseFeaturesInnerPropertiesChantierInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiltreGet200ResponseFeaturesInnerPropertiesChantierInner {
    if (json == null) {
        return json;
    }
    return {
        
        'idChantier': json['idChantier'] == null ? undefined : json['idChantier'],
        'nom': json['nom'] == null ? undefined : json['nom'],
    };
}

export function FiltreGet200ResponseFeaturesInnerPropertiesChantierInnerToJSON(json: any): FiltreGet200ResponseFeaturesInnerPropertiesChantierInner {
    return FiltreGet200ResponseFeaturesInnerPropertiesChantierInnerToJSONTyped(json, false);
}

export function FiltreGet200ResponseFeaturesInnerPropertiesChantierInnerToJSONTyped(value?: FiltreGet200ResponseFeaturesInnerPropertiesChantierInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idChantier': value['idChantier'],
        'nom': value['nom'],
    };
}

