/* tslint:disable */
/* eslint-disable */
/**
 * Service Tableau d\'Assemblage
 * API pour accéder aux données du tableau d\'assemblage, y compris les couches chantier, filtres et produits téléchargeables.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProduitGet200ResponseFeaturesInner } from './ProduitGet200ResponseFeaturesInner';
import {
    ProduitGet200ResponseFeaturesInnerFromJSON,
    ProduitGet200ResponseFeaturesInnerFromJSONTyped,
    ProduitGet200ResponseFeaturesInnerToJSON,
    ProduitGet200ResponseFeaturesInnerToJSONTyped,
} from './ProduitGet200ResponseFeaturesInner';

/**
 * 
 * @export
 * @interface ProduitGet200Response
 */
export interface ProduitGet200Response {
    /**
     * 
     * @type {string}
     * @memberof ProduitGet200Response
     */
    type?: string;
    /**
     * 
     * @type {Array<ProduitGet200ResponseFeaturesInner>}
     * @memberof ProduitGet200Response
     */
    features?: Array<ProduitGet200ResponseFeaturesInner>;
}

/**
 * Check if a given object implements the ProduitGet200Response interface.
 */
export function instanceOfProduitGet200Response(value: object): value is ProduitGet200Response {
    return true;
}

export function ProduitGet200ResponseFromJSON(json: any): ProduitGet200Response {
    return ProduitGet200ResponseFromJSONTyped(json, false);
}

export function ProduitGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProduitGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'features': json['features'] == null ? undefined : ((json['features'] as Array<any>).map(ProduitGet200ResponseFeaturesInnerFromJSON)),
    };
}

export function ProduitGet200ResponseToJSON(json: any): ProduitGet200Response {
    return ProduitGet200ResponseToJSONTyped(json, false);
}

export function ProduitGet200ResponseToJSONTyped(value?: ProduitGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'features': value['features'] == null ? undefined : ((value['features'] as Array<any>).map(ProduitGet200ResponseFeaturesInnerToJSON)),
    };
}

