/* tslint:disable */
/* eslint-disable */
/**
 * Service Tableau d\'Assemblage
 * API pour accéder aux données du tableau d\'assemblage, y compris les couches chantier, filtres et produits téléchargeables.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProduitGet200ResponseFeaturesInnerProperties
 */
export interface ProduitGet200ResponseFeaturesInnerProperties {
    /**
     * Identifiant unique
     * @type {string}
     * @memberof ProduitGet200ResponseFeaturesInnerProperties
     */
    id?: string;
    /**
     * Nom de la donnée
     * @type {string}
     * @memberof ProduitGet200ResponseFeaturesInnerProperties
     */
    name?: string;
    /**
     * URL de téléchargement de la donnée
     * @type {string}
     * @memberof ProduitGet200ResponseFeaturesInnerProperties
     */
    url?: string;
    /**
     * Nom à donnée à la dalle téléchargé
     * @type {string}
     * @memberof ProduitGet200ResponseFeaturesInnerProperties
     */
    nomTelechargement?: string;
    /**
     * Id du chantier auquel apartient la donnée
     * @type {string}
     * @memberof ProduitGet200ResponseFeaturesInnerProperties
     */
    idChantier?: string;
    /**
     * Date de création de la donnée
     * @type {Date}
     * @memberof ProduitGet200ResponseFeaturesInnerProperties
     */
    timestamp?: Date;
    /**
     * Légende à afficher au survole de la donnée dans l'interface
     * @type {string}
     * @memberof ProduitGet200ResponseFeaturesInnerProperties
     */
    legende?: string;
    /**
     * Niveau d'apparition de la couchedans l'interface de téléchargement
     * @type {number}
     * @memberof ProduitGet200ResponseFeaturesInnerProperties
     */
    zoomStart?: number;
    /**
     * Niveau de disparition de la couche dans l'interface de téléchargement
     * @type {number}
     * @memberof ProduitGet200ResponseFeaturesInnerProperties
     */
    zoomStop?: number;
}

/**
 * Check if a given object implements the ProduitGet200ResponseFeaturesInnerProperties interface.
 */
export function instanceOfProduitGet200ResponseFeaturesInnerProperties(value: object): value is ProduitGet200ResponseFeaturesInnerProperties {
    return true;
}

export function ProduitGet200ResponseFeaturesInnerPropertiesFromJSON(json: any): ProduitGet200ResponseFeaturesInnerProperties {
    return ProduitGet200ResponseFeaturesInnerPropertiesFromJSONTyped(json, false);
}

export function ProduitGet200ResponseFeaturesInnerPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProduitGet200ResponseFeaturesInnerProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'url': json['url'] == null ? undefined : json['url'],
        'nomTelechargement': json['nomTelechargement'] == null ? undefined : json['nomTelechargement'],
        'idChantier': json['id_chantier'] == null ? undefined : json['id_chantier'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'legende': json['legende'] == null ? undefined : json['legende'],
        'zoomStart': json['zoomStart'] == null ? undefined : json['zoomStart'],
        'zoomStop': json['zoomStop'] == null ? undefined : json['zoomStop'],
    };
}

export function ProduitGet200ResponseFeaturesInnerPropertiesToJSON(json: any): ProduitGet200ResponseFeaturesInnerProperties {
    return ProduitGet200ResponseFeaturesInnerPropertiesToJSONTyped(json, false);
}

export function ProduitGet200ResponseFeaturesInnerPropertiesToJSONTyped(value?: ProduitGet200ResponseFeaturesInnerProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'url': value['url'],
        'nomTelechargement': value['nomTelechargement'],
        'id_chantier': value['idChantier'],
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString().substring(0,10)),
        'legende': value['legende'],
        'zoomStart': value['zoomStart'],
        'zoomStop': value['zoomStop'],
    };
}

