/* tslint:disable */
/* eslint-disable */
/**
 * Service Tableau d\'Assemblage
 * API pour accéder aux données du tableau d\'assemblage, y compris les couches chantier, filtres et produits téléchargeables.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProduitGet200ResponseFeaturesInnerProperties } from './ProduitGet200ResponseFeaturesInnerProperties';
import {
    ProduitGet200ResponseFeaturesInnerPropertiesFromJSON,
    ProduitGet200ResponseFeaturesInnerPropertiesFromJSONTyped,
    ProduitGet200ResponseFeaturesInnerPropertiesToJSON,
    ProduitGet200ResponseFeaturesInnerPropertiesToJSONTyped,
} from './ProduitGet200ResponseFeaturesInnerProperties';
import type { ChantierGet200ResponseFeaturesInnerGeometry } from './ChantierGet200ResponseFeaturesInnerGeometry';
import {
    ChantierGet200ResponseFeaturesInnerGeometryFromJSON,
    ChantierGet200ResponseFeaturesInnerGeometryFromJSONTyped,
    ChantierGet200ResponseFeaturesInnerGeometryToJSON,
    ChantierGet200ResponseFeaturesInnerGeometryToJSONTyped,
} from './ChantierGet200ResponseFeaturesInnerGeometry';

/**
 * 
 * @export
 * @interface ProduitGet200ResponseFeaturesInner
 */
export interface ProduitGet200ResponseFeaturesInner {
    /**
     * 
     * @type {string}
     * @memberof ProduitGet200ResponseFeaturesInner
     */
    type?: string;
    /**
     * 
     * @type {ChantierGet200ResponseFeaturesInnerGeometry}
     * @memberof ProduitGet200ResponseFeaturesInner
     */
    geometry?: ChantierGet200ResponseFeaturesInnerGeometry;
    /**
     * 
     * @type {ProduitGet200ResponseFeaturesInnerProperties}
     * @memberof ProduitGet200ResponseFeaturesInner
     */
    properties?: ProduitGet200ResponseFeaturesInnerProperties;
}

/**
 * Check if a given object implements the ProduitGet200ResponseFeaturesInner interface.
 */
export function instanceOfProduitGet200ResponseFeaturesInner(value: object): value is ProduitGet200ResponseFeaturesInner {
    return true;
}

export function ProduitGet200ResponseFeaturesInnerFromJSON(json: any): ProduitGet200ResponseFeaturesInner {
    return ProduitGet200ResponseFeaturesInnerFromJSONTyped(json, false);
}

export function ProduitGet200ResponseFeaturesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProduitGet200ResponseFeaturesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'geometry': json['geometry'] == null ? undefined : ChantierGet200ResponseFeaturesInnerGeometryFromJSON(json['geometry']),
        'properties': json['properties'] == null ? undefined : ProduitGet200ResponseFeaturesInnerPropertiesFromJSON(json['properties']),
    };
}

export function ProduitGet200ResponseFeaturesInnerToJSON(json: any): ProduitGet200ResponseFeaturesInner {
    return ProduitGet200ResponseFeaturesInnerToJSONTyped(json, false);
}

export function ProduitGet200ResponseFeaturesInnerToJSONTyped(value?: ProduitGet200ResponseFeaturesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'geometry': ChantierGet200ResponseFeaturesInnerGeometryToJSON(value['geometry']),
        'properties': ProduitGet200ResponseFeaturesInnerPropertiesToJSON(value['properties']),
    };
}

