/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelechargementIndexRouteImport } from './routes/telechargement/index'
import { Route as TelechargementDownloadUrlRouteImport } from './routes/telechargement/$downloadUrl'

const TelechargementIndexRoute = TelechargementIndexRouteImport.update({
  id: '/telechargement/',
  path: '/telechargement/',
  getParentRoute: () => rootRouteImport,
} as any)
const TelechargementDownloadUrlRoute =
  TelechargementDownloadUrlRouteImport.update({
    id: '/telechargement/$downloadUrl',
    path: '/telechargement/$downloadUrl',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/telechargement/$downloadUrl': typeof TelechargementDownloadUrlRoute
  '/telechargement': typeof TelechargementIndexRoute
}
export interface FileRoutesByTo {
  '/telechargement/$downloadUrl': typeof TelechargementDownloadUrlRoute
  '/telechargement': typeof TelechargementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/telechargement/$downloadUrl': typeof TelechargementDownloadUrlRoute
  '/telechargement/': typeof TelechargementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/telechargement/$downloadUrl' | '/telechargement'
  fileRoutesByTo: FileRoutesByTo
  to: '/telechargement/$downloadUrl' | '/telechargement'
  id: '__root__' | '/telechargement/$downloadUrl' | '/telechargement/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TelechargementDownloadUrlRoute: typeof TelechargementDownloadUrlRoute
  TelechargementIndexRoute: typeof TelechargementIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telechargement/': {
      id: '/telechargement/'
      path: '/telechargement'
      fullPath: '/telechargement'
      preLoaderRoute: typeof TelechargementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telechargement/$downloadUrl': {
      id: '/telechargement/$downloadUrl'
      path: '/telechargement/$downloadUrl'
      fullPath: '/telechargement/$downloadUrl'
      preLoaderRoute: typeof TelechargementDownloadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  TelechargementDownloadUrlRoute: TelechargementDownloadUrlRoute,
  TelechargementIndexRoute: TelechargementIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
